# **1. Perkenalan Dataset**

**sumber dataset**: diperoleh melalui kaggle dengan judul "Red Wine Quality" yang menilai kualitas wine berdasarkan beberapa metrik dan hasil akhir pada column quality dengan score 0 hingga 10

side note: kolom quality dengan nilai kontinu bisa dibuat menjadi diskrit dengan menetapkan labeling untuk kriteria tertentu misalnya jika quality > 6.5 akan dilabeli bad

# **2. Import Library**

Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning atau deep learning.

In [1]:
# Data manipulation
import pandas as pd
import numpy as np
# Visualization
import matplotlib.pyplot as plt
import seaborn as sns
# Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
# Model
from sklearn.ensemble import RandomForestClassifier
# Evaluation
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score, roc_curve

# **3. Memuat Dataset**

Pada tahap ini, Anda perlu memuat dataset ke dalam notebook. Jika dataset dalam format CSV, Anda bisa menggunakan pustaka pandas untuk membacanya. Pastikan untuk mengecek beberapa baris awal dataset untuk memahami strukturnya dan memastikan data telah dimuat dengan benar.

Jika dataset berada di Google Drive, pastikan Anda menghubungkan Google Drive ke Colab terlebih dahulu. Setelah dataset berhasil dimuat, langkah berikutnya adalah memeriksa kesesuaian data dan siap untuk dianalisis lebih lanjut.

Jika dataset berupa unstructured data, silakan sesuaikan dengan format seperti kelas Machine Learning Pengembangan atau Machine Learning Terapan

In [2]:
# Download kaggle dataset

!chmod 600 kaggle.json
!kaggle datasets download -d uciml/red-wine-quality-cortez-et-al-2009

!unzip red-wine-quality-cortez-et-al-2009.zip 'winequality-red.csv'

chmod: cannot access 'kaggle.json': No such file or directory
Dataset URL: https://www.kaggle.com/datasets/uciml/red-wine-quality-cortez-et-al-2009
License(s): DbCL-1.0
Downloading red-wine-quality-cortez-et-al-2009.zip to /content
100% 25.6k/25.6k [00:00<00:00, 48.2MB/s]

Archive:  red-wine-quality-cortez-et-al-2009.zip
  inflating: winequality-red.csv

In [3]:
# Load dataset
df = pd.read_csv('/content/winequality-red.csv')
# Tampilkan data awal
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

# **4. Exploratory Data Analysis (EDA)**

Pada tahap ini, Anda akan melakukan **Exploratory Data Analysis (EDA)** untuk memahami karakteristik dataset.

Tujuan dari EDA adalah untuk memperoleh wawasan awal yang mendalam mengenai data dan menentukan langkah selanjutnya dalam analisis atau pemodelan.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

semua kolom memiliki nilai kontinu dikarenakan tiap fitur adalah pengukuran kimiawi dalam tiap wine

In [5]:
desc = df.describe()
display(desc)

print("\nInsight otomatis:")
for col in desc.columns:
    print(f"Column {col}: mean={desc[col]['mean']:.2f}, std={desc[col]['std']:.2f}")

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

Insight otomatis:
Column fixed acidity: mean=8.32, std=1.74
Column volatile acidity: mean=0.53, std=0.18
Column citric acid: mean=0.27, std=0.19
Column residual sugar: mean=2.54, std=1.41
Column chlorides: mean=0.09, std=0.05
Column free sulfur dioxide: mean=15.87, std=10.46
Column total sulfur dioxide: mean=46.47, std=32.90
Column density: mean=1.00, std=0.00
Column pH: mean=3.31, std=0.15
Column sulphates: mean=0.66, std=0.17
Column alcohol: mean=10.42, std=1.07
Column quality: mean=5.64, std=0.81

penjelasan metric

**keasaman:**
* Fixed acidity: kadar zat asam bawaan dari anggur yang sukar menguap (dasar dari keasaman wine, cthnya: asam tartrat, asam malat, asam sitrat)
* Volatile acidity: kadar asam asetat (mirip seperti cuka) yang menambah wangi wine
* citric acid: kadar asam sitrat dalam sejumlah anggur, menambah kesegaran ataupun keasaman wine yang kurang berasa

**zat yang mengawetkan:**
<br>sulfur dioksida/sulfit adalah kandungan utama yang digunakan pabrik untuk mengawetkan wine dan menghambat pertumbuhan bakteri dan ragi liar
* free sulfur dioxide: kadar sulfit yang aktif
* total sulfur dioxide: total kadar sulfit aktif dan sulfit yang sudah terikat ke molekul lain seperti gula dan aldehida
* sulphates: produk samping hasil fermentasi (sulfat)

ciri fisik:
<br>
* Density: semakin tinggi alkohol setelah proses fermentasi maka kadar air menurun
* pH: ph rendah (2.9-3.3)menghasilkan rasa asam dan rasa tidak tertinggal di tenggorokan, umumnya ada pada anggur putih. ph tinggi (3.4-4.0) memiliki rasa yang lebih lembut, tetapi lebih rawan mengalami pertumbuhan bakteri, umumnya ada pada anggur merah.
alcohol: kadar alcohol dalam wine, semakin tinggi semakin meninggalkan rasa yang panas

# **5. Data Preprocessing**

Pada tahap ini, data preprocessing adalah langkah penting untuk memastikan kualitas data sebelum digunakan dalam model machine learning.

Jika Anda menggunakan data teks, data mentah sering kali mengandung nilai kosong, duplikasi, atau rentang nilai yang tidak konsisten, yang dapat memengaruhi kinerja model. Oleh karena itu, proses ini bertujuan untuk membersihkan dan mempersiapkan data agar analisis berjalan optimal.

Berikut adalah tahapan-tahapan yang bisa dilakukan, tetapi **tidak terbatas** pada:
1. Menghapus atau Menangani Data Kosong (Missing Values)
2. Menghapus Data Duplikat
3. Normalisasi atau Standarisasi Fitur
4. Deteksi dan Penanganan Outlier
5. Encoding Data Kategorikal
6. Binning (Pengelompokan Data)

Cukup sesuaikan dengan karakteristik data yang kamu gunakan yah. Khususnya ketika kami menggunakan data tidak terstruktur.

In [6]:
# Cek Missing Value
print("=== Missing Value ===")
print(df.isnull().sum())

=== Missing Value ===
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [7]:
# Cek Duplikasi
print("\n=== Jumlah Duplikasi ===")
print(df.duplicated().sum())

=== Jumlah Duplikasi ===
240

In [8]:
# Drop Duplikasi
df = df.drop_duplicates()
# Cek ulang
print("\n=== Jumlah Data Setelah Drop Duplikasi ===")
print(df.shape)

=== Jumlah Data Setelah Drop Duplikasi ===
(1359, 12)

In [9]:
# encoding untuk quality > 6.5 menjadi angka 1 untuk good
df['quality'] = np.where(df['quality'] > 6.5, 1, 0)

display(df.head())

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,0
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,0

In [10]:
X = df.drop('quality', axis=1)
y = df['quality']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled,
                                                    y,
                                                    test_size=0.2,
                                                    random_state=42)